org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
MYAPP_UPLOAD_STORE_FILE=release.keystore
MYAPP_UPLOAD_KEY_ALIAS=mobilecloud
MYAPP_UPLOAD_STORE_PASSWORD=mobilecloud123
MYAPP_UPLOAD_KEY_PASSWORD=mobilecloud123
newArchEnabled=false
hermesEnabled=true
